#!/bin/bash

# parse argument
if [ "$1" != "" ]; then
    user_hostname=$1
else
    echo "Specify hostname as a positional parameter"
    exit
fi

# check for elevated priv
if [[ $(/usr/bin/id -u) != "0" ]]; then
    echo "This script needs to be run as root"
    exit
fi

# detect original hostname
old_hostname=$(cut -d ' ' -f4 /etc/hosts)

# edit /etc/hosts
/usr/bin/sed -i "s/$old_hostname/$user_hostname/" /etc/hosts

# change hostname
/usr/bin/hostname $user_hostname 

# edit /etc/sysconfig/network
/usr/bin/echo "HOSTNAME=$user_hostname" >> /etc/sysconfig/network

# notify user to reboot for full change to take effect
echo "Hostname has been changed to $user_hostname. Reboot the machine for the change to take full effect."


